package constants

const (
	PACKAGE_KAFKA_READER_RECEIVE_MESSAGE = "[PACKAGE-KAFKA-READER-RECEIVE-MESSAGE]: "
	PACKAGE_KAFKA_WRITER_SEND_MESSAGE    = "[PACKAGE-KAFKA-WRITER-SEND-MESSAGE]: "
	PACKAGE_KAFKA_CREATE_TOPIC           = "[PACKAGE-KAFKA-CREATE-TOPIC]: "
	PACKAGE_KAFKA_GET_LIST_TOPIC         = "[PACKAGE-KAFKA-GET_LIST-TOPIC]: "
)
